# --- GO DEMO APP (KOBAY) ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demoApp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoApp
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
      - name: demo
        image: demoapp:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  labels:
    app: demoApp
spec:
  selector:
    app: demoApp
  ports:
    - name: http-metrics 
      port: 80
      targetPort: 8080
---
# Prometheus Monitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: demoApp
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 5s
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  labels:
    app: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      containers:
      - name: ai-cont
        image: ai-image:v2 
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: ai-service
spec:
  selector:
    app: ai
  ports:
    - name: http-metrics 
      port: 80
      targetPort: 5000
  type: NodePort